name: lets_dance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
#  firebase_auth: ^0.14.0+5
  firebase_auth: ^3.1.10
 # cloud_firestore: ^0.12.9+4
  cloud_firestore: ^3.1.9
  firebase_storage: ^10.2.17
  firebase: ^9.0.3
  provider: ^4.0.0
  flutter_spinkit: ^4.0.0
  file_picker: ^4.1.3
  open_file: ^3.2.1
  path_provider: ^2.0.10
  video_player: ^2.1.10
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  inview_notifier_list: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/backgrounds/pic1.jpg
     - images/backgrounds/pic2.jpg
     - images/backgrounds/pic3.JPG
     - images/backgrounds/pic4.jpeg
     - images/backgrounds/pic5.jpg
     - images/background_images/0.jpg
     - images/background_images/1.jpg
     - images/background_images/2.jpg
     - images/background_images/3.jpg
     - images/background_images/4.jpg
     - images/background_images/5.jpg
     - images/background_images/6.jpg
     - images/background_images/7.jpg
     - images/background_images/8.jpg
     - images/background_images/9.jpg
     - images/background_images/10.jpg
     - images/background_images/11.jpg
     - images/background_images/12.jpg
     - images/background_images/13.jpg
     - images/background_images/14.jpg
     - images/background_images/15.jpg
     - images/background_images/16.jpg
     - images/background_images/17.jpg
     - images/background_images/18.jpg
     - images/background_images/19.jpg
     - images/background_images/20.jpg
     - images/background_images/21.jpg
     - images/background_images/22.jpg
     - images/background_images/23.jpg
     - images/background_images/24.jpg
     - images/background_images/25.jpg
     - images/background_images/26.jpg
     - images/background_images/27.jpg
     - images/background_images/28.jpg
     - images/background_images/29.jpg
     - images/background_images/30.jpg
     - images/background_images/31.jpg
     - images/background_images/32.jpg
     - images/background_images/33.jpg
     - images/background_images/34.jpg
     - images/background_images/35.jpg
     - images/background_images/36.jpg
     - images/background_images/37.jpg
     - images/background_images/38.jpg
     - images/background_images/39.jpg
     - images/background_images/40.jpg
     - images/background_images/41.jpg
     - images/background_images/42.jpg
     - images/background_images/43.jpg
     - images/background_images/44.jpg
     - images/background_images/45.jpg
     - images/background_images/46.jpg
     - images/background_images/47.jpg
     - images/background_images/48.jpg
     - images/background_images/49.jpg
     - images/background_images/50.jpg
     - images/background_images/51.jpg
     - images/faces/Angle.png
     - images/faces/Angry.png
     - images/faces/Bazz.png
     - images/faces/Beast.png
     - images/faces/Belle.png
     - images/faces/Boy.png
     - images/faces/Cinderella.png
     - images/faces/Crazy.png
     - images/faces/Crying.png
     - images/faces/Dollar.png
     - images/faces/Elsa.png
     - images/faces/Flower-Girl.png
     - images/faces/Genie.png
     - images/faces/Girl.png
     - images/faces/Glasses.png
     - images/faces/Kiss.png
     - images/faces/Laugh.png
     - images/faces/Laugh-2.png
     - images/faces/MiniMouse.png
     - images/faces/Nerd.png
     - images/faces/NerdGirl.png
     - images/faces/Piggi.png
     - images/faces/Red-Angry.png
     - images/faces/Shocking.png
     - images/faces/Simba.png
     - images/faces/Star-Wars.png
     - images/faces/Stitch.png
     - images/faces/Sun.png
     - images/faces/Tinkerbell.png
     - images/faces/Unicorn-Poop.png
     - images/faces/Winking-Girl.png
     - images/avatars/green.png
     - images/avatars/green_purple.png
     - images/avatars/pink_light_blue_yellow.png
     - images/avatars/purple_pink_yellow.png
     - videos/final_hadar2.mp4
     - google_fonts/josefin_sans/
     - google_fonts/Passion_One/
     - google_fonts/Signika/
     - google_fonts/Signika_Negative/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
