// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1sPXraANkU16aa5HfPlA8fHua-Q55AI',
    appId: '1:392463651691:web:39dde60cfab156cffc322e',
    messagingSenderId: '392463651691',
    projectId: 'let-s-dance-a0be2',
    authDomain: 'let-s-dance-a0be2.firebaseapp.com',
    databaseURL: 'https://let-s-dance-a0be2-default-rtdb.firebaseio.com',
    storageBucket: 'let-s-dance-a0be2.appspot.com',
    measurementId: 'G-5RBM6QJ3NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0o5ioA2FbYU5IzSvUGU-TjMsCwIWZr4',
    appId: '1:392463651691:android:e21761c761189877fc322e',
    messagingSenderId: '392463651691',
    projectId: 'let-s-dance-a0be2',
    databaseURL: 'https://let-s-dance-a0be2-default-rtdb.firebaseio.com',
    storageBucket: 'let-s-dance-a0be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBgJewI0x7LvwzpDDUOKn64lKHXoc08Y',
    appId: '1:392463651691:ios:39a8c932b21422fdfc322e',
    messagingSenderId: '392463651691',
    projectId: 'let-s-dance-a0be2',
    databaseURL: 'https://let-s-dance-a0be2-default-rtdb.firebaseio.com',
    storageBucket: 'let-s-dance-a0be2.appspot.com',
    iosClientId: '392463651691-u9coqlahliqng7r3vs4ud930f25rs4qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsDance',
  );
}
